### PR TITLE
Feature/storybook integration

### PR DESCRIPTION
**Pull request by sunguru98**
My first PR in story book integration. This PR is just for initializing the storybook onto our application. Let me know if I made any bloopers haha.

### CODE REVIEW

**Comment by youngkidwarrior** [comment]
@sunguru98 thanks for this. Can you `git reset` the merge and `git pull origin master --rebase` instead

**Comment by sunguru98** [comment]
Donezo ..

**Comment by youngkidwarrior** [comment]
@sunguru98 

Can you add the ability to toggle the storybook

https://sophieau.com/article/react-native-storybook/

You can make a new PR for this. Checkout a new branch off of this one and set it to merge into this PR

**Comment by sunguru98** [comment]
@youngkidwarrior, this was actually wired inside (if you could look at the Root.tsx, you can see the exact code snippet) ..

**Pull request merged**
